# Generated by Django 6.0.7 on 2026-07-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('jersey_number', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=200)),
            ],
        ),
    ]
